# RDS Clean Databases
Gabriel Ferreira

In [1]:
# Imports
from sqlalchemy import create_engine
from sqlalchemy import text
import pandas as pd
import os
from dotenv import load_dotenv
from pyspark.sql import SparkSession

In [2]:
# LOAD ENV
load_dotenv("/home/jovyan/work/.env")

RDS_HOST = os.getenv("RDS_HOST")
RDS_PORT = os.getenv("RDS_PORT")
RDS_DATABASE = os.getenv("RDS_DATABASE")
RDS_USER = os.getenv("RDS_USER")
RDS_PASSWORD = os.getenv("RDS_PASSWORD")

In [3]:
# RDS CONNECTION
engine = create_engine(

    f"postgresql+psycopg2://{RDS_USER}:"
    f"{RDS_PASSWORD}@"
    f"{RDS_HOST}:{RDS_PORT}/"
    f"{RDS_DATABASE}"

)

In [4]:
# Creating Spark session

spark = SparkSession.builder \
    .appName("FraudDetectionML") \
    .config(
        "spark.jars",
        "/home/jovyan/work/jars/hadoop-aws-3.3.4.jar,/home/jovyan/work/jars/aws-java-sdk-bundle-1.12.262.jar"
    ) \
    .config(
        "spark.hadoop.fs.s3a.impl",
        "org.apache.hadoop.fs.s3a.S3AFileSystem"
    ) \
    .config(
        "spark.hadoop.fs.s3a.aws.credentials.provider",
        "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    ) \
    .getOrCreate()

**1st run -- script 03_fraud_inference.py**

In [5]:
df_predictions = spark.read.parquet(
    "s3a://fraud-detection-data-lake-200702211381/gold/fraud_predictions/"
)

print(df_predictions.count())

100000

**1st run -- script 04_write_predictions_to_rds.py**

In [6]:
# Validar RDS
query = """
SELECT COUNT(*) AS total_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows
0      100000

**2st run -- script 03_fraud_inference.py**

In [7]:
df_predictions = spark.read.parquet(
    "s3a://fraud-detection-data-lake-200702211381/gold/fraud_predictions/"
)

print(df_predictions.count())

200000

**2st run -- script 04_write_predictions_to_rds.py****

In [8]:
# Validar RDS
query = """
SELECT COUNT(*) AS total_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows
0      200000

In [9]:
# Validar Duplicidade depois da 2nd run
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT trans_num) AS unique_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows  unique_rows
0      200000       200000

**5st run -- script 03_fraud_inference.py**

In [10]:
df_predictions = spark.read.parquet(
    "s3a://fraud-detection-data-lake-200702211381/gold/fraud_predictions/"
)

print(df_predictions.count())

500000

**5st run -- script 04_write_predictions_to_rds.py**

In [11]:
# Validar RDS
query = """
SELECT COUNT(*) AS total_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows
0      500000

In [12]:
# Validar Duplicidade depois da 5th run
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT trans_num) AS unique_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows  unique_rows
0      500000       500000

**10st run -- script 03_fraud_inference.py**

In [13]:
df_predictions = spark.read.parquet(
    "s3a://fraud-detection-data-lake-200702211381/gold/fraud_predictions/"
)

print(df_predictions.count())

1000000

**10st run -- script 04_write_predictions_to_rds.py**

In [14]:
# Validar RDS
query = """
SELECT COUNT(*) AS total_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows
0     1000000

In [15]:
# Validar Duplicidade depois da 10st run
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT trans_num) AS unique_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows  unique_rows
0     1000000      1000000

**13st run -- script 03_fraud_inference.py**

In [16]:
df_predictions = spark.read.parquet(
    "s3a://fraud-detection-data-lake-200702211381/gold/fraud_predictions/"
)

print(df_predictions.count())

1300000

**13st run -- script 04_write_predictions_to_rds.py**

In [17]:
# Validar RDS
query = """
SELECT COUNT(*) AS total_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows
0     1300000

In [19]:
# Validar Duplicidade depois da 13st run
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT trans_num) AS unique_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows  unique_rows
0     1300000      1300000

**14st run -- script 03_fraud_inference.py (LAST RUN)**

In [20]:
df_predictions = spark.read.parquet(
    "s3a://fraud-detection-data-lake-200702211381/gold/fraud_predictions/"
)

print(df_predictions.count())

1316675

**14st run -- script 04_write_predictions_to_rds.py (LAST RUN)**

In [21]:
# Validar RDS
query = """
SELECT COUNT(*) AS total_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows
0     1316675

In [22]:
# Validar Duplicidade depois da last run
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT trans_num) AS unique_rows
FROM fraud_predictions;
"""

pd.read_sql(query, engine)

   total_rows  unique_rows
0     1316675      1316675